name: GitHub Actions Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .venv/web/Tests

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: venv setup
        uses: srvanderplas/action-setup-venv@v1.1.5
        with:
          cache-dependency-path: /requirements.txt
          #venv-dir: # optional, default is venv
          # Command to install python dependencies.
          install-cmd: if ! test -f **requirements*.txt; then echo "No requirements files"; else python3 -m pip install -r **requirements*.txt; fi
                
      - name: Test with pytest
        run: |
          python -m pytest
    

          
 
