name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: checkout   
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: latest
          install-dependencies: true
          install-chromedriver: true

      - name: SeleniumCICD
         # You may pin to the exact commit or the version.
         # uses: nakajiss/DockerSeleniumAction@e6ea7ae921226473af620875a8853bad0750a033
        uses: nakajiss/DockerSeleniumAction@v1.3.7
        with:
           test-plan-path: enviroment/web/Tests/test_mainweb.py
                             
      - name: Run tests
        working-directory: enviroment/web/Tests
        run: python -m pytest
