name: Run Test via Pytest

on:
   push:
     branches : [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cambiar directorio de trabajo
        working-directory: ./.venv/srcweb
      - name: Test with pytest
        run: |
          pytest
      - name: Generate Coverage Report
        run: |
          coverage report -m