name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4' # Reemplaza con la versión de Python que uses
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate  # En Linux/macOS
          # En Windows: venv\Scripts\activate
          python -m pip install -r .venv/requirements.txt # Si tienes un archivo requirements.txt
          python -m pip install pytest
      - name: Run tests
        run: |
          source venv/bin/activate  # En Linux/macOS
          # En Windows: venv\Scripts\activate
          pytest 
