name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-22.04    

    steps:
      - name: Checkout   
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install selenium
          python -m pip install pytest    

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run tests
        run: |
          python  -m pytest test_main_web.py
        working-directory: enviroment/web/Tests
