name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout   
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          #python -m pip install selenium
          python -m pip install pytest  

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.0.0
        with:
          chrome-version: 'stable'
          install-chromedriver: 'true'

      - name: Run tests
        working-directory: enviroment/web/Tests
        run: |
          python  -m pytest -v
        
