name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .venv

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv .venv
          source .venv/bin/activate
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                 
      - name: Run tests
        run: |
          working-directory: .venv/web/Tests
          python -m pytest
           
