name: GitHub Actions Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.x"
      
      - name: venv setup
        uses: srvanderplas/action-setup-venv@v1.1.5
        with:
          cache-dependency-path: .venv/requirements.txt
          venv-dir: .venv
          # Command to install python dependencies.
          install-cmd: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                
      - name: Test with pytest
        run: pytest
    

          
 
