name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
defaults:
  run:
    working-directory: /opt/hostedtoolcache/Python/3.13.4/x64
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: checkout   
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install selenium
          python -m pip install pytest    

      - name: Run tests
        working-directory: enviroment/web/Tests
        run: pytest
