name: Run Test via Pytest

on:
   push:
     branches : [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ["3.13.4"]
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
    
            
      
            
      
      
